# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

name: $(MajorVersion).$(MinorVersion).$(PatchVersion)

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '28ddc8b4-48bd-4be8-bd65-4b94a64aa330'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'rowdychildren-dockerhub'
        repository: 'rowdychildren/duckbot'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(MajorVersion).$(MinorVersion).$(PatchVersion)
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'duckbotazure'
        KeyVaultName: 'duckbotdeploy'
        SecretsFilter: 'duckbotppe-discord'
        RunAsPreJob: true
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'duckbotazure'
        subscriptionId: 'ba91aca8-b156-4d64-8673-564050f2f5f1'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'duckbotppe'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: 'deploy.json'
        overrideParameters: '-deploymentName "duckbotppe" -discordBotToken "$(duckbotppe-discord)" -image "rowdychildren/duckbot:$(tag)"'
        deploymentMode: 'Incremental'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: 'deploy.json'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'